### ISSUE TITLE
Request single record

### ISSUE THREAD

**Issue by jonearley** [mlibrary/pride#14]
Suggestion: `Pride.requestRecord(datastore_uid, record_uid)`

Is it possible to build a request for a single record? I suspect it would need at minimum a datastore unique id and a record unique id.

The goal is to be able to create a full record view in search with a url route that looks similar to this: [/mirlyn/001294948](#)
[/<datastore_uid>/<record_uid>](#)

**Comment by bertrama** [comment]
a3dceb0befab4026de17371aeb76e2beb60cea36: Added `Pride.requestRecord(datastore_uid, record_uid, func)` where `func` is optional, and does the same thing as `Pride.Core.Record#renderFull(func)`.  Returns a new Pride.Core.Record instance.
