### ISSUE TITLE
Add observers for when datastores are not available

### ISSUE THREAD

**Issue by jonearley** [mlibrary/pride#20]
If a datastore is not responding as usual could Pride alert an observer with an appropriate message? It would be helpful to know if a datastore is down for whatever reason -- such as maintenance, unexpected error -- and then handle it in the UI.

**Comment by bertrama** [comment]
That's what the [messenger is for](https://github.com/mlibrary/pride/blob/master/source/singletons/messenger.js), right?

**Comment by jonearley** [comment]
I think so, yeah.

**Comment by justcolin** [comment]
Let me know if you want the story behind the Messenger and why that implementation was commented out.
