### ISSUE TITLE
Add `requestHoldings()` functionality to record returned by `requestRecord()`

### ISSUE THREAD

**Issue by jonearley** [mlibrary/pride#21]
This will be necessary for rendering holdings when loading a full record url directly.

**Comment by bertrama** [comment]
Is this different from `getHoldings()`:
```
Pride.requestRecord('mirlyn', '000680427').getHoldings(function(x) {console.log(x)});
```

**Comment by jonearley** [comment]
Whoops. I was mistakenly running `getHoldings()` on the returned record, not on `requestRecord()`. Got it.
